name: phy2
dependencies:
  - python
  - pip
  - numpy
  - matplotlib
  - scipy
  - h5py
  - pyqt
  - cython
  - pip:
    - colorcet
    - pyopengl
    - qtconsole
    - requests
    - traitlets
    - PyQtWebEngine
    - tqdm
    - joblib
    - click
    - mkdocs==1.0.4
    - git+https://github.com/cortex-lab/phy.git@dev
    - git+https://github.com/cortex-lab/phylib.git
