site_name: phy
pages:
- Getting started:
  - Introduction: 'index.md'
  - Release notes: 'release.md'
  - Installation: 'installation.md'
- User guide:
  - Terminology: 'terminology.md'
  - Interactive visualization: 'visualization.md'
  - Manual clustering: 'clustering.md'
  - Keyboard shortcuts and snippets: 'shortcuts.md'
- Developer guide:
  - Customization: 'customization.md'
  - Plugin examples: 'plugins.md'
  - API documentation: 'api.md'
theme: readthedocs
