site_name: phy
pages:
- Home: 'index.md'
- GUI: 'gui.md'
- Plotting: 'plot.md'
- Manual clustering: 'clustering.md'
- Configuration and plugin system: 'config.md'
- Command-line interface: 'cli.md'
theme: readthedocs
